# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ :name => 'Chicago' }, { :name => 'Copenhagen' }])
#   Mayor.create(:name => 'Daley', :city => cities.first)

#Groups
eleven = Group.create(:name => '11 Year Olds', :age => 11)
troop = Group.create(:name => 'Troop', :age => 12)
team = Group.create(:name => 'Team', :age => 14)
crew = Group.create(:name => 'Crew', :age => 16)
adult = Group.create(:name => 'Adult Leader', :age => 18)

#Addresses
#For sample purposes only
cliff = Address.create(:street => '1911 Doniphan Ave', :city => 'St. Joseph', :state => 'MO', :zip => '64503')
john = Address.create(:street => '3309 Sacramento', :city => 'St. Joseph', :state => 'MO', :zip => '64503')
dad = Address.create(:street => '4910 Woodfield Dr', :city => 'St. Joseph', :state => 'MO', :zip => '64503')
one = Address.create(:street => '400 E 220 W', :city => 'St. Joseph', :state => 'MO', :zip => '64503')
two = Address.create(:street => '1234 Rennick', :city => 'St. Joseph', :state => 'MO', :zip => '64503')
three = Address.create(:street => 'In a van down by the river', :city => 'St. Joseph', :state => 'MO', :zip => '64503')
four = Address.create(:street => '19 Quaker Ridge Rd.', :city => 'St. Joseph', :state => 'MO', :zip => '64503')
five = Address.create(:street => '1000 Coney Island Ave.', :city => 'St. Joseph', :state => 'MO', :zip => '64503')
six = Address.create(:street => '2962 Dunedin Cv', :city => 'St. Joseph', :state => 'MO', :zip => '64503')
seven = Address.create(:street => '1500 Vance Ave', :city => 'St. Joseph', :state => 'MO', :zip => '64503')


#Scouters
#For sample purposes only
#Adults:
Scouter.create(:first => 'Cliff', :last => 'Hales', :birthday => '9/8/1978', :phone => '801-443-4814', :cell => '307-871-1032', :email => 'cliff@thekeet.com', :password => 'blank', :address => cliff, :group => adult)
Scouter.create(:first => 'John', :last => 'Hales', :birthday => '3/22/1980', :phone => '810-444-4444', :cell => '321-456-4566', :email => 'a@b.com', :password => 'blank', :address => john, :group => adult)
Scouter.create(:first => 'Jay', :last => 'Hales', :birthday => '1/27/1956', :phone => '810-444-4444', :cell => '321-456-4566', :email => 'a@b.com', :password => 'blank', :address => dad, :group => adult)
Scouter.create(:first => 'Frank', :last => 'Marcucci', :birthday => '7/10/1943', :phone => '712-748-5088', :cell => '712-748-5088', :email => 'Frank.L.Marcucci@spambob.com', :password => 'lichaec7Zoh', :address => six, :group => adult)
Scouter.create(:first => 'Robert', :last => 'Michaels', :birthday => '3/1/1963', :phone => '347-860-7797', :cell => '347-860-7797', :email => 'Robert.D.Michaels@trashymail.com', :password => 'ha9Ua8ooK', :address => seven, :group => adult)

#11 Year olds
Scouter.create(:first => 'T.J.', :last => 'Cantwell', :birthday => '1/1/1999', :phone => '810-444-4444', :cell => '321-456-4566', :email => 'a@b.com', :password => 'blank', :address => seven, :group => eleven)
Scouter.create(:first => 'Guillermo', :last => 'Cochran', :birthday => '2/11/1960', :phone => '907-244-2083', :cell => '907-244-2083', :email => 'Guillermo.W.Cochran@pookmail.com', :password => 'ohl0Eizoopei', :address => one, :group => eleven)
Scouter.create(:first => 'Salvatore', :last => 'Duchene', :birthday => '5/12/1982', :phone => '512-353-9714', :cell => '512-353-9714', :email => 'Salvatore.T.Duchene@pookmail.com', :password => 'fooRafe7ahph', :address => one, :group => eleven)
Scouter.create(:first => 'Gary', :last => 'Burns', :birthday => '4/10/1967', :phone => '720-290-4950', :cell => '720-290-4950', :email => 'Gary.B.Burns@spambob.com', :password => 'ohg0aePoa', :address => one, :group => eleven)
#Troop
Scouter.create(:first => 'Rafael', :last => 'Hollis', :birthday => '3/10/1965', :phone => '410-754-0600', :cell => '410-754-0600', :email => 'Rafael.S.Hollis@pookmail.com', :password => 'oe4IiGiengie', :address => two, :group => troop)
Scouter.create(:first => 'Jose', :last => 'Hartwick', :birthday => '4/23/1967', :phone => '425-877-5177', :cell => '425-877-5177', :email => 'Jose.P.Hartwick@mailinator.com', :password => 'ok9Aefuu2', :address => two, :group => troop)
Scouter.create(:first => 'David', :last => 'Gonzalez', :birthday => '1/24/1940', :phone => '205-275-6136', :cell => '205-275-6136', :email => 'David.M.Gonzalez@dodgit.com', :password => 'lailei1Shosh', :address => two, :group => troop)
Scouter.create(:first => 'Antonio', :last => 'Thompson', :birthday => '10/10/1975', :phone => '570-561-5006', :cell => '570-561-5006', :email => 'Antonio.C.Thompson@pookmail.com', :password => 'Iexaech6', :address => two, :group => troop)
Scouter.create(:first => 'Troy', :last => 'Jerez', :birthday => '8/7/1944', :phone => '212-264-0408', :cell => '212-264-0408', :email => 'Troy.M.Jerez@mailinator.com', :password => 'eiW0oonao0C', :address => two, :group => troop)
Scouter.create(:first => 'Jon', :last => 'Halstead', :birthday => '7/31/1966', :phone => '718-343-0867', :cell => '718-343-0867', :email => 'Jon.R.Halstead@trashymail.com', :password => 'ooBeiphuiH5b', :address => two, :group => troop)
Scouter.create(:first => 'Elias', :last => 'Smith', :birthday => '9/17/1979', :phone => '443-914-5817', :cell => '443-914-5817', :email => 'Elias.R.Smith@mailinator.com', :password => 'wah7AiPah', :address => two, :group => troop)
Scouter.create(:first => 'Nathan', :last => 'Peck', :birthday => '1/25/1942', :phone => '760-676-5343', :cell => '760-676-5343', :email => 'Nathan.T.Peck@spambob.com', :password => 'phaiD1Elee', :address => two, :group => troop)
Scouter.create(:first => 'James', :last => 'Clark', :birthday => '11/26/1956', :phone => '336-325-3258', :cell => '336-325-3258', :email => 'James.V.Clark@trashymail.com', :password => 'eeM2giaGuCie', :address => two, :group => troop)
Scouter.create(:first => 'Juan', :last => 'Hendricks', :birthday => '10/4/1962', :phone => '918-656-1898', :cell => '918-656-1898', :email => 'Juan.H.Hendricks@dodgit.com', :password => 'xe9mah0Vu2so', :address => two, :group => troop)
Scouter.create(:first => 'Elliott', :last => 'Joseph', :birthday => '2/8/1982', :phone => '605-394-7683', :cell => '605-394-7683', :email => 'Elliott.S.Joseph@spambob.com', :password => 'biel4vo9D', :address => two, :group => troop)
Scouter.create(:first => 'Clyde', :last => 'Adams', :birthday => '6/30/1956', :phone => '717-600-1856', :cell => '717-600-1856', :email => 'Clyde.S.Adams@trashymail.com', :password => 'lii8INi6ah', :address => two, :group => troop)
Scouter.create(:first => 'Mickey', :last => 'Westgate', :birthday => '4/23/1945', :phone => '804-647-6314', :cell => '804-647-6314', :email => 'Mickey.K.Westgate@mailinator.com', :password => 'aSa9goh7x', :address => two, :group => troop)
Scouter.create(:first => 'George', :last => 'Tran', :birthday => '1/21/1951', :phone => '253-651-9346', :cell => '253-651-9346', :email => 'George.J.Tran@pookmail.com', :password => 'avu5Iu4thai', :address => two, :group => troop)
Scouter.create(:first => 'Joel', :last => 'Mcculley', :birthday => '5/14/1981', :phone => '504-684-5867', :cell => '504-684-5867', :email => 'Joel.C.Mcculley@dodgit.com', :password => 'cish3Phiu', :address => two, :group => troop)
Scouter.create(:first => 'Nathanael', :last => 'Campos', :birthday => '8/10/1962', :phone => '864-982-6830', :cell => '864-982-6830', :email => 'Nathanael.A.Campos@mailinator.com', :password => 'eiCie9Ahri', :address => two, :group => troop)

#Team
Scouter.create(:first => 'William', :last => 'Buchanan', :birthday => '12/14/1947', :phone => '605-867-4758', :cell => '605-867-4758', :email => 'William.P.Buchanan@trashymail.com', :password => 'ipiePohga5e', :address => three, :group => team)
Scouter.create(:first => 'Timothy', :last => 'Machado', :birthday => '1/26/1948', :phone => '928-329-1186', :cell => '928-329-1186', :email => 'Timothy.M.Machado@trashymail.com', :password => 'eeBa5ke7oh', :address => three, :group => team)
Scouter.create(:first => 'Ernest', :last => 'Hughey', :birthday => '10/9/1978', :phone => '360-921-4786', :cell => '360-921-4786', :email => 'Ernest.M.Hughey@trashymail.com', :password => 'eiR1iep7ahw', :address => three, :group => team)
Scouter.create(:first => 'Patrick', :last => 'Sullivan', :birthday => '7/20/1958', :phone => '931-409-9511', :cell => '931-409-9511', :email => 'Patrick.G.Sullivan@spambob.com', :password => 'Ahwu0aeL7', :address => three, :group => team)
Scouter.create(:first => 'Jeffery', :last => 'Donley', :birthday => '6/10/1985', :phone => '541-759-8963', :cell => '541-759-8963', :email => 'Jeffery.L.Donley@spambob.com', :password => 'Da7bie9s', :address => three, :group => team)
Scouter.create(:first => 'Joseph', :last => 'Pendley', :birthday => '6/7/1947', :phone => '731-808-2371', :cell => '731-808-2371', :email => 'Joseph.S.Pendley@trashymail.com', :password => 'Quailail4e', :address => three, :group => team)
Scouter.create(:first => 'Brian', :last => 'Currier', :birthday => '12/4/1957', :phone => '310-829-3906', :cell => '310-829-3906', :email => 'Brian.J.Currier@mailinator.com', :password => 'hi8ahF1gah', :address => three, :group => team)
Scouter.create(:first => 'Philip', :last => 'Barth', :birthday => '9/15/1978', :phone => '630-689-7613', :cell => '630-689-7613', :email => 'Philip.S.Barth@spambob.com', :password => 'oos2Dayah', :address => three, :group => team)
Scouter.create(:first => 'Charles', :last => 'Pichardo', :birthday => '8/25/1977', :phone => '910-738-7024', :cell => '910-738-7024', :email => 'Charles.A.Pichardo@dodgit.com', :password => 'ga8Ahxocei', :address => three, :group => team)
Scouter.create(:first => 'James', :last => 'Lecompte', :birthday => '12/12/1969', :phone => '607-627-3722', :cell => '607-627-3722', :email => 'James.M.Lecompte@dodgit.com', :password => 'Vu6eiw5Eish', :address => three, :group => team)
Scouter.create(:first => 'Edward', :last => 'Valadez', :birthday => '2/27/1966', :phone => '347-225-8064', :cell => '347-225-8064', :email => 'Edward.W.Valadez@dodgit.com', :password => 'Chaith8ai', :address => three, :group => team)
Scouter.create(:first => 'Robert', :last => 'Estrada', :birthday => '6/11/1963', :phone => '413-732-8742', :cell => '413-732-8742', :email => 'Robert.L.Estrada@trashymail.com', :password => 'Naadais0', :address => three, :group => team)
Scouter.create(:first => 'Kennith', :last => 'Sherron', :birthday => '5/24/1952', :phone => '740-525-0861', :cell => '740-525-0861', :email => 'Kennith.J.Sherron@pookmail.com', :password => 'quoh5aecaiN', :address => three, :group => team)
Scouter.create(:first => 'Jim', :last => 'Wilson', :birthday => '1/10/1943', :phone => '805-783-0126', :cell => '805-783-0126', :email => 'Jim.F.Wilson@trashymail.com', :password => 'onooTun1oo', :address => three, :group => team)

#Crew
Scouter.create(:first => 'Arthur', :last => 'Hill', :birthday => '1/8/1971', :phone => '401-765-2566', :cell => '401-765-2566', :email => 'Arthur.J.Hill@pookmail.com', :password => 'ahSooGhae2ai', :address => four, :group => crew)
Scouter.create(:first => 'John', :last => 'Rios', :birthday => '2/27/1965', :phone => '914-955-5199', :cell => '914-955-5199', :email => 'John.W.Rios@spambob.com', :password => 'ai3IuCh3', :address => four, :group => crew)
Scouter.create(:first => 'Christopher', :last => 'Murphy', :birthday => '8/21/1944', :phone => '541-967-0785', :cell => '541-967-0785', :email => 'Christopher.J.Murphy@mailinator.com', :password => 'vees0Phaegah', :address => four, :group => crew)
Scouter.create(:first => 'David', :last => 'Gamble', :birthday => '5/17/1964', :phone => '305-226-0181', :cell => '305-226-0181', :email => 'David.M.Gamble@trashymail.com', :password => 'Moy2ohhughe', :address => four, :group => crew)
Scouter.create(:first => 'Christopher', :last => 'Brown', :birthday => '6/9/1945', :phone => '618-210-5429', :cell => '618-210-5429', :email => 'Christopher.K.Brown@spambob.com', :password => 'eeChu8VoCoh', :address => four, :group => crew)
Scouter.create(:first => 'Michael', :last => 'Mcghee', :birthday => '6/5/1972', :phone => '561-904-8592', :cell => '561-904-8592', :email => 'Michael.M.Mcghee@pookmail.com', :password => 'Eeva3eeth', :address => four, :group => crew)
Scouter.create(:first => 'John', :last => 'Green', :birthday => '9/9/1952', :phone => '920-664-3806', :cell => '920-664-3806', :email => 'John.A.Green@dodgit.com', :password => 'maKiN9IeWe', :address => four, :group => crew)
Scouter.create(:first => 'Adam', :last => 'Manning', :birthday => '4/29/1967', :phone => '518-325-9369', :cell => '518-325-9369', :email => 'Adam.C.Manning@mailinator.com', :password => 'AetheiGh1qu', :address => four, :group => crew)
Scouter.create(:first => 'William', :last => 'Knutson', :birthday => '10/29/1945', :phone => '763-531-6912', :cell => '763-531-6912', :email => 'William.J.Knutson@pookmail.com', :password => 'Ohcoo1Oo', :address => four, :group => crew)



#award_types
rank = AwardType.create(:name => 'Rank')
required = AwardType.create(:name => 'Required Merit Bage')
elective = AwardType.create(:name => 'Elective Merit Badge')
adult = AwardType.create(:name => 'Adult Award')
religious = AwardType.create(:name => 'Religious')
other = AwardType.create(:name => 'Other')

#Awards
#Ranks
Scout = Award.create(:name => 'Scout', :order => 1, :award_type => rank)
Tenderfoot = Award.create(:name => 'Tenderfoot', :order => 2, :award_type => rank)
SecondClass = Award.create(:name => 'Second Class', :order => 3, :award_type => rank)
FirstClass = Award.create(:name => 'First Class', :order => 4, :award_type => rank)
Star = Award.create(:name => 'Star', :order => 5, :award_type => rank)
Life = Award.create(:name => 'Life', :order => 6, :award_type => rank)
Eagle = Award.create(:name => 'Eagle', :order => 7, :award_type => rank)


#Required Merit Badges
Camping = Award.create(:name => 'Camping', :order => 1, :award_type => required)
CitizenshipintheCommunity = Award.create(:name => 'Citizenship in the Community', :order => 1, :award_type => required)
CitizenshipintheNation = Award.create(:name => 'Citizenship in the Nation', :order => 1, :award_type => required)
CitizenshipintheWorld = Award.create(:name => 'Citizenship in the World', :order => 1, :award_type => required)
Communications = Award.create(:name => 'Communications', :order => 1, :award_type => required)
Cycling = Award.create(:name => 'Cycling', :order => 1, :award_type => required)
EmergencyPreparedness = Award.create(:name => 'Emergency Preparedness', :order => 1, :award_type => required)
EnvironmentalScience = Award.create(:name => 'Environmental Science', :order => 1, :award_type => required)
FamilyLife = Award.create(:name => 'Family Life', :order => 1, :award_type => required)
FirstAid = Award.create(:name => 'First Aid', :order => 1, :award_type => required)
Hiking = Award.create(:name => 'Hiking', :order => 1, :award_type => required)
Lifesaving = Award.create(:name => 'Lifesaving', :order => 1, :award_type => required)
PersonalFitness = Award.create(:name => 'Personal Fitness', :order => 1, :award_type => required)
PersonalManagement = Award.create(:name => 'Personal Management', :order => 1, :award_type => required)
Swimming = Award.create(:name => 'Swimming', :order => 1, :award_type => required)

#Elective Merit Badges
AmericanBusiness = Award.create(:name => 'American Business', :order => 1, :award_type => elective)
AmericanCultures = Award.create(:name => 'American Cultures', :order => 1, :award_type => elective)
AmericanHeritage = Award.create(:name => 'American Heritage', :order => 1, :award_type => elective)
AmericanLabor = Award.create(:name => 'American Labor', :order => 1, :award_type => elective)
AnimalScience = Award.create(:name => 'Animal Science', :order => 1, :award_type => elective)
Archaeology = Award.create(:name => 'Archaeology', :order => 1, :award_type => elective)
Archery = Award.create(:name => 'Archery', :order => 1, :award_type => elective)
Architecture = Award.create(:name => 'Architecture', :order => 1, :award_type => elective)
Art = Award.create(:name => 'Art', :order => 1, :award_type => elective)
Astronomy = Award.create(:name => 'Astronomy', :order => 1, :award_type => elective)
Athletics = Award.create(:name => 'Athletics', :order => 1, :award_type => elective)
NuclearScience = Award.create(:name => 'Nuclear Science', :order => 1, :award_type => elective)
AutomotiveMaintenance = Award.create(:name => 'Automotive Maintenance', :order => 1, :award_type => elective)
Aviation = Award.create(:name => 'Aviation', :order => 1, :award_type => elective)
Backpacking = Award.create(:name => 'Backpacking', :order => 1, :award_type => elective)
Basketry = Award.create(:name => 'Basketry', :order => 1, :award_type => elective)
BirdStudy = Award.create(:name => 'Bird Study', :order => 1, :award_type => elective)
Bugling = Award.create(:name => 'Bugling', :order => 1, :award_type => elective)
Canoeing = Award.create(:name => 'Canoeing', :order => 1, :award_type => elective)
Chemistry = Award.create(:name => 'Chemistry', :order => 1, :award_type => elective)
Cinematography = Award.create(:name => 'Cinematography', :order => 1, :award_type => elective)
Climbing = Award.create(:name => 'Climbing', :order => 1, :award_type => elective)
CoinCollecting = Award.create(:name => 'Coin Collecting', :order => 1, :award_type => elective)
Collections = Award.create(:name => 'Collections', :order => 1, :award_type => elective)
CompositeMaterials = Award.create(:name => 'Composite Materials', :order => 1, :award_type => elective)
Computers = Award.create(:name => 'Computers', :order => 1, :award_type => elective)
Cooking = Award.create(:name => 'Cooking', :order => 1, :award_type => elective)
CrimePrevention = Award.create(:name => 'Crime Prevention', :order => 1, :award_type => elective)
Dentistry = Award.create(:name => 'Dentistry', :order => 1, :award_type => elective)
DisabilitiesAwareness = Award.create(:name => 'Disabilities Awareness', :order => 1, :award_type => elective)
DogCare = Award.create(:name => 'Dog Care', :order => 1, :award_type => elective)
Drafting = Award.create(:name => 'Drafting', :order => 1, :award_type => elective)
Electricity = Award.create(:name => 'Electricity', :order => 1, :award_type => elective)
Electronics = Award.create(:name => 'Electronics', :order => 1, :award_type => elective)
Energy = Award.create(:name => 'Energy', :order => 1, :award_type => elective)
Engineering = Award.create(:name => 'Engineering', :order => 1, :award_type => elective)
Entrepreneurship = Award.create(:name => 'Entrepreneurship', :order => 1, :award_type => elective)
FarmMechanics = Award.create(:name => 'Farm Mechanics', :order => 1, :award_type => elective)
Fingerprinting = Award.create(:name => 'Fingerprinting', :order => 1, :award_type => elective)
FireSafety = Award.create(:name => 'Fire Safety', :order => 1, :award_type => elective)
FishAndWildlifeManagement = Award.create(:name => 'Fish And Wildlife Management', :order => 1, :award_type => elective)
Fishing = Award.create(:name => 'Fishing', :order => 1, :award_type => elective)
FlyFishing = Award.create(:name => 'Fly Fishing', :order => 1, :award_type => elective)
Forestry = Award.create(:name => 'Forestry', :order => 1, :award_type => elective)
Gardening = Award.create(:name => 'Gardening', :order => 1, :award_type => elective)
Genealogy = Award.create(:name => 'Genealogy', :order => 1, :award_type => elective)
Geology = Award.create(:name => 'Geology', :order => 1, :award_type => elective)
Golf = Award.create(:name => 'Golf', :order => 1, :award_type => elective)
GraphicArts = Award.create(:name => 'Graphic Arts', :order => 1, :award_type => elective)
HomeRepairs = Award.create(:name => 'Home Repairs', :order => 1, :award_type => elective)
Horsemanship = Award.create(:name => 'Horsemanship', :order => 1, :award_type => elective)
IndianLore = Award.create(:name => 'Indian Lore', :order => 1, :award_type => elective)
InsectStudy = Award.create(:name => 'Insect Study', :order => 1, :award_type => elective)
Journalism = Award.create(:name => 'Journalism', :order => 1, :award_type => elective)
LandscapeArchitecture = Award.create(:name => 'Landscape Architecture', :order => 1, :award_type => elective)
Law = Award.create(:name => 'Law', :order => 1, :award_type => elective)
Leatherwork = Award.create(:name => 'Leatherwork', :order => 1, :award_type => elective)
MammalStudy = Award.create(:name => 'Mammal Study', :order => 1, :award_type => elective)
Medicine = Award.create(:name => 'Medicine', :order => 1, :award_type => elective)
Metalwork = Award.create(:name => 'Metalwork', :order => 1, :award_type => elective)
ModelDesignAndBuilding = Award.create(:name => 'Model Design And Building', :order => 1, :award_type => elective)
Motorboating = Award.create(:name => 'Motorboating', :order => 1, :award_type => elective)
Music = Award.create(:name => 'Music', :order => 1, :award_type => elective)
Nature = Award.create(:name => 'Nature', :order => 1, :award_type => elective)
NuclearScience = Award.create(:name => 'Nuclear Science', :order => 1, :award_type => elective)
Oceanography = Award.create(:name => 'Oceanography', :order => 1, :award_type => elective)
Orienteering = Award.create(:name => 'Orienteering', :order => 1, :award_type => elective)
Painting = Award.create(:name => 'Painting', :order => 1, :award_type => elective)
Pets = Award.create(:name => 'Pets', :order => 1, :award_type => elective)
Photography = Award.create(:name => 'Photography', :order => 1, :award_type => elective)
Pioneering = Award.create(:name => 'Pioneering', :order => 1, :award_type => elective)
PlantScience = Award.create(:name => 'Plant Science', :order => 1, :award_type => elective)
Plumbing = Award.create(:name => 'Plumbing', :order => 1, :award_type => elective)
Pottery = Award.create(:name => 'Pottery', :order => 1, :award_type => elective)
PublicHealth = Award.create(:name => 'Public Health', :order => 1, :award_type => elective)
PublicSpeaking = Award.create(:name => 'Public Speaking', :order => 1, :award_type => elective)
PulpAndPaper = Award.create(:name => 'Pulp And Paper', :order => 1, :award_type => elective)
Radio = Award.create(:name => 'Radio', :order => 1, :award_type => elective)
Railroading = Award.create(:name => 'Railroading', :order => 1, :award_type => elective)
Reading = Award.create(:name => 'Reading', :order => 1, :award_type => elective)
ReptileAndAmphibianStudy = Award.create(:name => 'Reptile And Amphibian Study', :order => 1, :award_type => elective)
RifleShooting = Award.create(:name => 'Rifle Shooting', :order => 1, :award_type => elective)
Rowing = Award.create(:name => 'Rowing', :order => 1, :award_type => elective)
Safety = Award.create(:name => 'Safety', :order => 1, :award_type => elective)
Salesmanship = Award.create(:name => 'Salesmanship', :order => 1, :award_type => elective)
Scholarship = Award.create(:name => 'Scholarship', :order => 1, :award_type => elective)
ScubaDiving = Award.create(:name => 'Scuba Diving', :order => 1, :award_type => elective)
Sculpture = Award.create(:name => 'Sculpture', :order => 1, :award_type => elective)
ShotgunShooting = Award.create(:name => 'Shotgun Shooting', :order => 1, :award_type => elective)
Skating = Award.create(:name => 'Skating', :order => 1, :award_type => elective)
SmallBoatSailing = Award.create(:name => 'Small-Boat Sailing', :order => 1, :award_type => elective)
SnowSports = Award.create(:name => 'Snow Sports', :order => 1, :award_type => elective)
SoilAndWaterConservation = Award.create(:name => 'Soil And Water Conservation', :order => 1, :award_type => elective)
SpaceExploration = Award.create(:name => 'Space Exploration', :order => 1, :award_type => elective)
Sports = Award.create(:name => 'Sports', :order => 1, :award_type => elective)
StampCollecting = Award.create(:name => 'Stamp Collecting', :order => 1, :award_type => elective)
Surveying = Award.create(:name => 'Surveying', :order => 1, :award_type => elective)
Textile = Award.create(:name => 'Textile', :order => 1, :award_type => elective)
Theater = Award.create(:name => 'Theater', :order => 1, :award_type => elective)
TrafficSafety = Award.create(:name => 'Traffic Safety', :order => 1, :award_type => elective)
TruckTransportation = Award.create(:name => 'Truck Transportation', :order => 1, :award_type => elective)
VeterinaryMedicine = Award.create(:name => 'Veterinary Medicine', :order => 1, :award_type => elective)
WaterSports = Award.create(:name => 'Water Sports', :order => 1, :award_type => elective)
Weather = Award.create(:name => 'Weather', :order => 1, :award_type => elective)
Whitewater = Award.create(:name => 'Whitewater', :order => 1, :award_type => elective)
WildernessSurvival = Award.create(:name => 'Wilderness Survival', :order => 1, :award_type => elective)
WoodCarving = Award.create(:name => 'Wood Carving', :order => 1, :award_type => elective)
Woodwork = Award.create(:name => 'Woodwork', :order => 1, :award_type => elective)


#Adult Award
GoodjobLeader = Award.create(:name => 'Good job Leader', :order => 1, :award_type => adult)
SilverBeaver = Award.create(:name => 'Silver Beaver', :order => 1, :award_type => adult)


#Religious
DutytoGodDeacons = Award.create(:name => 'Duty to God (Deacons)', :order => 1, :award_type => religious)
DutytoGodTeachers = Award.create(:name => 'Duty to God (Teachers)', :order => 2, :award_type => religious)
DutytoGodPriests = Award.create(:name => 'Duty to God (Priests)', :order => 3, :award_type => religious)

#Other
Palm1 = Award.create(:name => 'Palm 1', :order => 1, :award_type => other)
Palm2 = Award.create(:name => 'Palm 2', :order => 2, :award_type => other)
Palm3 = Award.create(:name => 'Palm 3', :order => 3, :award_type => other)

#Requirements (leaving otherrequirementID blank)
#Scout
Requirement.create(:award => Scout, :order =>1, :number => '1', :text => 'Meet age requirements: Be a boy who is 11 years old, or one who has completed the fifth grade or earned the Arrow of Light Award and is at least 10 years old, but is not yet 18 years old.')
Requirement.create(:award => Scout, :order =>1, :number => '2', :text => 'Complete a Boy Scout application and health history signed by your parent or guardian.')
Requirement.create(:award => Scout, :order =>1, :number => '3', :text => 'Find a Scout troop near your home. (To find a troop, contact your local Boy Scout Council.  The Council name, address and phone number can be found on BSA\'s Council Locator Page.)')
Requirement.create(:award => Scout, :order =>1, :number => '4', :text => 'Repeat the Pledge of Allegiance.')
Requirement.create(:award => Scout, :order =>1, :number => '5', :text => 'Demonstrate the Scout sign, salute, and handshake.')
Requirement.create(:award => Scout, :order =>1, :number => '6', :text => 'Demonstrate tying the square knot (a joining knot).')
Requirement.create(:award => Scout, :order =>1, :number => '7', :text => 'Understand and agree to live by the Scout Oath or Promise, Law, motto, and slogan, and the Outdoor Code.')
Requirement.create(:award => Scout, :order =>1, :number => '8', :text => 'Describe the Scout badge.')
Requirement.create(:award => Scout, :order =>1, :number => '9', :text => 'Complete the Pamphlet Exercises. With your parent or guardian, complete the exercises in the pamphlet "How to Protect Your Children from Child Abuse: A Parent\'s Guide".')
Requirement.create(:award => Scout, :order =>1, :number => '10', :text => 'Participate in a Scoutmaster conference. Turn in your Boy Scout application and health history form signed by your parent or guardian, then participate in a Scoutmaster conference.')

#Tenderfoot
Requirement.create(:award => Tenderfoot, :order =>1, :number => '1', :text => 'Present yourself to your leader, properly dressed, before going on an overnight camping trip. Show the camping gear you will use. Show the right way to pack and carry it.')
Requirement.create(:award => Tenderfoot, :order =>2, :number => '2', :text => 'Spend at least one night on a patrol or troop campout. Sleep in a tent you have helped pitch.')
Requirement.create(:award => Tenderfoot, :order =>3, :number => '3', :text => 'On the campout, assist in preparing and cooking one of your patrol\'s meals.  Tell why it is important for each patrol member to share in meal preparation and cleanup, and explain the importance of eating together.')
Requirement.create(:award => Tenderfoot, :order =>4, :number => '4a', :text => 'Demonstrate how to whip and fuse the ends of a rope.')
Requirement.create(:award => Tenderfoot, :order =>5, :number => '4b', :text => 'Demonstrate that you know how to tie the following knots and tell what their uses are: two half hitches and the taut-line hitch.')
Requirement.create(:award => Tenderfoot, :order =>6, :number => '4c', :text => 'Using the EDGE method teach another person how to tie the square knot.')
Requirement.create(:award => Tenderfoot, :order =>7, :number => '5', :text => 'Explain the rules of safe hiking, both on the highway and cross-country, during the day and at night. Explain what to do if you are lost.')
Requirement.create(:award => Tenderfoot, :order =>8, :number => '6', :text => 'Demonstrate how to display, raise, lower, and fold the American flag.')
Requirement.create(:award => Tenderfoot, :order =>9, :number => '7', :text => 'Repeat from memory and explain in your own words the Scout Oath, Law, motto, and slogan.')
Requirement.create(:award => Tenderfoot, :order =>10, :number => '8', :text => 'Know your patrol name, give the patrol yell, and describe your patrol flag.')
Requirement.create(:award => Tenderfoot, :order =>11, :number => '9', :text => 'Explain the importance of the buddy system as it relates to your personal safety on outings and in your neighborhood. Describe what a bully is and how you should respond to one.')
Requirement.create(:award => Tenderfoot, :order =>12, :number => '10a', :text => 'Record your best in the following tests: *  Push-ups * Pull-ups * Sit-ups * Standing long jump * 1/4 mile walk/run')
Requirement.create(:award => Tenderfoot, :order =>13, :number => '10b', :text => 'Show improvement in the activities listed in requirement 10a after practicing for 30 days.')
Requirement.create(:award => Tenderfoot, :order =>14, :number => '11', :text => 'Identify local poisonous plants; tell how to treat for exposure to them.')
Requirement.create(:award => Tenderfoot, :order =>15, :number => '12a', :text => 'Demonstrate how to care for someone who is choking.')
Requirement.create(:award => Tenderfoot, :order =>16, :number => '12b', :text => 'Show first aid for the following: * Simple cuts and scrapes * Blisters on the hand and foot * Minor (thermal/heat) burns or scalds (superficial, or first degree) * Bites and stings of insects and ticks * Venomous snakebite * Nosebleed * Frostbite and sunburn')
Requirement.create(:award => Tenderfoot, :order =>17, :number => '13', :text => 'Demonstrate scout spirit by living the Scout Oath (Promise) and Scout Law in your everyday life. Discuss four specific examples of how you have lived the points of the Scout Law in your daily life.')
Requirement.create(:award => Tenderfoot, :order =>18, :number => '14', :text => 'Participate in a Scoutmaster conference.')
Requirement.create(:award => Tenderfoot, :order =>19, :number => '15', :text => 'Complete your board of review')

#SecondClass
Requirement.create(:award => SecondClass, :order =>1, :number => '1a', :text => 'Demonstrate how a compass works and how to orient a map. Explain what map symbols mean.')
Requirement.create(:award => SecondClass, :order =>2, :number => '1b', :text => 'Using a compass and a map together, take a 5-mile hike (or 10 miles by bike) approved by your adult leader and your parent or guardian.*')
Requirement.create(:award => SecondClass, :order =>3, :number => '2', :text => 'Discuss the principles of "Leave No Trace"')
Requirement.create(:award => SecondClass, :order =>4, :number => '3a', :text => 'Since joining, have participated in five separate troop/patrol activities (other than troop/patrol meetings), two of which included camping overnight.')
Requirement.create(:award => SecondClass, :order =>5, :number => '3b', :text => 'On one of these campouts, select your patrol site and sleep in a tent that you pitched. Explain what factors you should consider when choosing a patrol site and where to pitch a tent.')
Requirement.create(:award => SecondClass, :order =>6, :number => '3c', :text => 'Demonstrate proper care, sharpening, and use of the knife, saw, and ax, and describe when they should be used.')
Requirement.create(:award => SecondClass, :order =>7, :number => '3d', :text => 'Use the tools listed in requirement 3c to prepare tinder, kindling, and fuel for a cooking fire.')
Requirement.create(:award => SecondClass, :order =>8, :number => '3e', :text => 'Discuss when it is appropriate to use a cooking fire and a lightweight stove. Discuss the safety procedures for using both..')
Requirement.create(:award => SecondClass, :order =>9, :number => '3f', :text => 'In an approved place and at an approved time, demonstrate how to build a fire and set up a lightweight stove. Note: Lighting the fire is not required.')
Requirement.create(:award => SecondClass, :order =>10, :number => '3g', :text => 'On one campout, plan and cook one hot breakfast or lunch, selecting foods from the food pyramid. Explain the importance of good nutrition. Tell how to transport, store, and prepare the foods you selected.')
Requirement.create(:award => SecondClass, :order =>11, :number => '4', :text => 'Participate in a flag ceremony for your school, religious institution, chartered organization, community, or troop activity. Explain to your leader what respect is due the flag of the United States.')
Requirement.create(:award => SecondClass, :order =>12, :number => '5', :text => 'Participate in an approved (minimum of one hour) service project.')
Requirement.create(:award => SecondClass, :order =>13, :number => '6', :text => 'Identify or show evidence of at least ten kinds of wild animals (birds, mammals, reptiles, fish, mollusks) found in your community.')
Requirement.create(:award => SecondClass, :order =>14, :number => '7a', :text => 'Show what to do for "hurry" cases of stopped breathing, serious bleeding, and ingested poisoning.')
Requirement.create(:award => SecondClass, :order =>15, :number => '7b', :text => 'Prepare a personal first aid kit to take with you on a hike.')
Requirement.create(:award => SecondClass, :order =>16, :number => '7c', :text => 'Demonstrate first aid for the following: * Object in the eye * Bite of a suspected rabid animal * Puncture wounds from a splinter, nail, and fishhook * Serious burns (partial thickness, or second degree)* Heat exhaustion * Shock * Heatstroke, dehydration, hypothermia, and hyperventilation')
Requirement.create(:award => SecondClass, :order =>17, :number => '8a', :text => 'Tell what precautions must be taken for a safe swim.')
Requirement.create(:award => SecondClass, :order =>18, :number => '8b', :text => 'Demonstrate your ability to jump feet first into water over your head in depth, level off and swim 25 feet on the surface, stop, turn sharply, resume swimming, then return to your starting place.')
Requirement.create(:award => SecondClass, :order =>19, :number => '8c', :text => 'Demonstrate water rescue methods by reaching with your arm or leg, by reaching with a suitable object, and by throwing lines and objects. Explain why swimming rescues should not be attempted when a reaching or throwing rescue is possible, and explain why and how a rescue swimmer should avoid contact with the victim.')
Requirement.create(:award => SecondClass, :order =>20, :number => '9a', :text => 'Participate in a school, community, or troop program on the dangers of using drugs, alcohol, and tobacco, and other practices that could be harmful to your health. Discuss your participation in the program with your family, and explain the dangers of substance addictions.')
Requirement.create(:award => SecondClass, :order =>21, :number => '9b', :text => 'Explain the three R\'s of personal safety and protection.')
Requirement.create(:award => SecondClass, :order =>22, :number => '10', :text => 'Earn an amount of money agreed upon by you and your parent, then save at least 50 percent of that money.')
Requirement.create(:award => SecondClass, :order =>23, :number => '11', :text => 'Demonstrate scout spirit by living the Scout Oath (Promise) and Scout Law in your everyday life. Discuss four specific examples (different from those used for Tenderfoot requirement 13) of how you have lived the points of the Scout Law in your daily life.')
Requirement.create(:award => SecondClass, :order =>24, :number => '12', :text => 'Participate in a Scoutmaster conference.')
Requirement.create(:award => SecondClass, :order =>25, :number => '13', :text => 'Complete your board of review.')

#FirstClass
Requirement.create(:award => FirstClass, :order =>1, :number => '1', :text => 'Demonstrate how to find directions during the day and at night without using a compass.')
Requirement.create(:award => FirstClass, :order =>2, :number => '2', :text => 'Using a map and compass, complete an orienteering course that covers at least one mile and requires measuring the height and/or width of designated items (tree, tower, canyon, ditch, etc.)')
Requirement.create(:award => FirstClass, :order =>3, :number => '3', :text => 'Since joining, have participated in ten separate troop/patrol activities (other than troop/patrol meetings), three of which included camping overnight. Demonstrate the principles of Leave No Trace on these outings.')
Requirement.create(:award => FirstClass, :order =>4, :number => '4a', :text => 'Help plan a patrol menu for one campout that includes at least one breakfast, one lunch, and one dinner and that requires cooking at least two of the meals. Tell how the menu includes the foods from the food pyramid and meets nutritional needs.')
Requirement.create(:award => FirstClass, :order =>5, :number => '4b', :text => 'Using the menu planned in requirement 4a, make a list showing the cost and food amounts needed to feed three or more boys and secure the ingredients.')
Requirement.create(:award => FirstClass, :order =>6, :number => '4c', :text => 'Tell which pans, utensils, and other gear will be needed to cook and serve these meals.')
Requirement.create(:award => FirstClass, :order =>7, :number => '4d', :text => 'Explain the procedures to follow in the safe handling and storage of fresh meats, dairy products, eggs, vegetables, and other perishable food products. Tell how to properly dispose of camp garbage, cans, plastic containers, and other rubbish.')
Requirement.create(:award => FirstClass, :order =>8, :number => '4e', :text => 'On one campout, serve as your patrol''s cook. Supervise your assistant(s) in using a stove or building a cooking fire. Prepare the breakfast, lunch, and dinner planned in requirement 4a. Lead your patrol in saying grace at the meals and supervise cleanup.')
Requirement.create(:award => FirstClass, :order =>9, :number => '5', :text => 'Visit and discuss with a selected individual approved by your leader (elected official, judge, attorney, civil servant, principal, teacher) your constitutional rights and obligations as a U.S. citizen.')
Requirement.create(:award => FirstClass, :order =>10, :number => '6', :text => 'Identify or show evidence of at least ten kinds of native plants found in your community.')
Requirement.create(:award => FirstClass, :order =>11, :number => '7a', :text => 'Discuss when you should and should not use lashings. Then demonstrate tying the timber hitch and clove hitch and their use in square, shear, and diagonal lashings by joining two or more poles or staves together.')
Requirement.create(:award => FirstClass, :order =>12, :number => '7b', :text => 'Use lashing to make a useful camp gadget.')
Requirement.create(:award => FirstClass, :order =>13, :number => '8a', :text => 'Demonstrate tying the bowline knot and describe several ways it can be used.')
Requirement.create(:award => FirstClass, :order =>14, :number => '8b', :text => 'Demonstrate bandages for a sprained ankle. and for injuries on the head, the upper arm, and the collarbone.')
Requirement.create(:award => FirstClass, :order =>15, :number => '8c', :text => 'Show how to transport by yourself, and with one other person, a person: * from a smoke-filled room * with a sprained ankle, for at least 25 yards.')
Requirement.create(:award => FirstClass, :order =>16, :number => '8d', :text => 'Tell the five most common signals of a heart attack. Explain the steps (procedures) in cardiopulmonary resuscitation (CPR).')
Requirement.create(:award => FirstClass, :order =>17, :number => '9a', :text => 'Tell what precautions must be taken for a safe trip afloat.')
Requirement.create(:award => FirstClass, :order =>18, :number => '9b', :text => 'Successfully complete the BSA swimmer test.')
Requirement.create(:award => FirstClass, :order =>19, :number => '9c', :text => 'With a helper and a practice victim, show a line rescue both as tender and rescuer. (The practice victim should be approximately 30 feet from shore in deep water.)')
Requirement.create(:award => FirstClass, :order =>20, :number => '10', :text => 'Tell someone who is eligible to join Boy Scouts, or an inactive Boy Scout, about your troop''s activities. Invite him to a troop outing, activity, service project or meeting. Tell him how to join, or encourage the inactive Boy Scout to become active.')
Requirement.create(:award => FirstClass, :order =>21, :number => '11', :text => 'Describe the three things you should avoid doing related to use of the Internet. Describe a cyberbully and how you should respond to one.')
Requirement.create(:award => FirstClass, :order =>22, :number => '12', :text => 'Demonstrate scout spirit by living the Scout Oath (Promise) and Scout Law in your everyday life. Discuss four specific examples (different from those used for Tenderfoot requirement 13 and Second Class requirement 11) of how you have lived the points of the Scout Law in your daily life.')
Requirement.create(:award => FirstClass, :order =>23, :number => '13', :text => 'Participate in a Scoutmaster conference.')
Requirement.create(:award => FirstClass, :order =>24, :number => '14', :text => 'Complete your board of review.')

#Star
Requirement.create(:award => Star, :order =>1, :number => '1', :text => 'Be active in your troop and patrol for at least 4 months as a First Class Scout.')
Requirement.create(:award => Star, :order =>1, :number => '2', :text => 'Demonstrate scout spirit by living the Scout Oath (Promise) and Scout Law in your everyday life.')
Requirement.create(:award => Star, :order =>1, :number => '3', :text => 'Earn 6 merit badges, including 4 from the required list for Eagle.*')
Requirement.create(:award => Star, :order =>1, :number => '4', :text => 'While a First Class Scout, take part in service projects totaling at least 6 hours of work. These projects must be approved by your Scoutmaster.')
Requirement.create(:award => Star, :order =>1, :number => '5', :text => 'While a First Class Scout, serve actively 4 months in one or more of the following positions of responsibility (or carry out a Scoutmaster-assigned leadership project to help the troop):')
Requirement.create(:award => Star, :order =>1, :number => '6', :text => 'Take part in a Scoutmaster conference')
Requirement.create(:award => Star, :order =>1, :number => '7', :text => 'Complete your board of review.')

#Life
Requirement.create(:award => Life, :order =>1, :number => '1', :text => 'Be active in your troop and patrol for at least 6 months as a Star Scout.')
Requirement.create(:award => Life, :order =>2, :number => '2', :text => 'Demonstrate Scout spirit by living the Scout Oath (Promise) and Scout Law in your everyday life.')
Requirement.create(:award => Life, :order =>3, :number => '3', :text => 'Earn 5 more merit badges (so that you have 11 in all), including any 3 more from the required list for Eagle.')
Requirement.create(:award => Life, :order =>4, :number => '4', :text => 'While a Star Scout, take part in service projects totaling at least 6 hours of work. These projects must be approved by your Scoutmaster.')
Requirement.create(:award => Life, :order =>5, :number => '5', :text => 'While a Star Scout, serve actively 6 months in one or more of the positions of responsibility listed in requirement 5 for Star Scout (or carry out a Scoutmaster-assigned leadership project to help the troop).')
Requirement.create(:award => Life, :order =>6, :number => '6', :text => 'While a Star Scout, use the EDGE method to teach a younger Scout the skills from ONE of the following six choices, so that he is prepared to pass those requirements to his unit leader\'s satisfaction.')
Requirement.create(:award => Life, :order =>7, :number => '6a', :text => 'Second Class - 7a and 7c (first aid)')
Requirement.create(:award => Life, :order =>8, :number => '6b', :text => 'Second Class - 1a (outdoor skills)')
Requirement.create(:award => Life, :order =>9, :number => '6c', :text => 'Second Class - 3c, 3d, 3e, and 3f (cooking/camping)')
Requirement.create(:award => Life, :order =>10, :number => '6d', :text => 'First Class - 8a, 8b, 8c, and 8d (first aid)')
Requirement.create(:award => Life, :order =>11, :number => '6e', :text => 'First Class - 1, 7a, and 7c (outdoor skills)')
Requirement.create(:award => Life, :order =>12, :number => '6f', :text => 'First Class - 4a, 4b, and 4d (cooking/camping)')
Requirement.create(:award => Life, :order =>13, :number => '7', :text => 'Take part in a Scoutmaster conference')
Requirement.create(:award => Life, :order =>14, :number => '8', :text => 'Complete your board of review.')

#Eagle
Requirement.create(:award => Eagle, :order =>1, :number => '1', :text => 'Be active in your troop, team, crew, or ship for a period of at least 6 months after you have achieved the rank of Life Scout.')
Requirement.create(:award => Eagle, :order =>1, :number => '2', :text => 'Demonstrate that you live by the principles of the Scout Oath and Law in your daily life. List the names of individuals who know you personally and would be willing to provide a recommendation on your behalf, including parents/guardians, religious, educational, and employer references.')
Requirement.create(:award => Eagle, :order =>1, :number => '3', :text => 'Earn a total of 21 merit badges (10 more than you already have), including the following:')
Requirement.create(:award => Eagle, :order =>1, :number => '4', :text => 'While a Life Scout, serve actively for a period of 6 months in one or more of the following positions of responsibility: ')
Requirement.create(:award => Eagle, :order =>1, :number => '5', :text => 'While a Life Scout, plan, develop, and give leadership to others in a service project helpful to any religious institution, any school, or your community. (The project should benefit an organization other than Boy Scouting.) The project plan must be approved by the organization benefiting from the effort, your Scoutmaster and troop committee and the council or district before you start. You must use the Eagle Scout Leadership Service Project Workbook, No. 521-927, in meeting this requirement.')
Requirement.create(:award => Eagle, :order =>1, :number => '6', :text => 'Take part in a Scoutmaster conference.')
Requirement.create(:award => Eagle, :order =>1, :number => '7', :text => 'Successfully complete an Eagle Scout board of review.')



